version: "3"

services: 
    syncer:
        container_name: notify_sync_${KEY}
        image: py38_slim_sync
        volumes:
            - /home/jumbo:/hostfs
            - /media:/target
            - ./app/output:/app/output
            - ./app/data:/app/data
        command: python3 app/sync.py ${IP} ${PATTERN} ${CONF} ${KEY}
